  Id CommandLine
  -- -----------
   1 try { . "c:\Users\matth\AppData\Local\Programs\Microsoft VS Code\072586267e\resources\a... "
   2 docker-compose down
   3 cd .\day_1\
   4 docker-compose down
   5 docker-compose up -d
   6 docker-compose down
   7 docker-compose up -d
   8 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:...
   9 docker exec -i spark-master bash
  10 docker exec -it spark-master bash
  11 docker exec -it namenode bash
  12 docker cp ./tp_projects/lic-data-2023.csv namenode:/lic-data-2023.csv
  13 docker exec -it namenode bash
  14 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  15 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:...
  16 docker exec -it namenode bash
  17 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  18 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  19 docker exec -it namenode bash
  20 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:...
  21 docker exec -it namenode bash
  22 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  23 docker exec -it namenode bash
  24 history
  25 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  26 docker exec -it namenode bash
  27 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  28 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:...
  29 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  30 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  31 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  32 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  33 docker exec -it namenode bash
  34 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  35 docker exec -it namenode bash
  36 clear
  37 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  38 ls
  39 docker-compose down
  40 docker-compose up -d
  41 docker-compose up -d
  42 docker-compose up -d
  43 docker-compose up -d
  44 docker exec -it namenode bash
  45 clear
  46 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  47 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  48 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  49 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  50 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  51 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:...
  52 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  53 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  54 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  55 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:...
  56 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  57 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  58 history
  59 git add .
  60 git commit -m 'tp3'
  61 git push
  62 docker cp ./tp_projects/ventes.csv namenode:/ventes.csv
  63 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  64 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  65 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:...
  66 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  67 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  68 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  69 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  70 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:...
  71 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  72 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:...
  73 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  74 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  75 docker exec -it spark-master /opt/spark/bin/spark-submit --master spark://spark-master:... 
  76 git add .
  77 git commit -m 'tp3'
  78 git push